FROM elixir:1.8.0

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /home/app
# REPLACE_OS_VARS=true _build/prod/rel/group_collect/bin/group_collect console
ENV PORT=5000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash
ADD ./.build_cache/ .
ADD ./docker/scripts/start-server.sh ./start-server.sh
EXPOSE 5000
CMD ["bin/group_collect", "foreground"]
